name: server

on:
#   schedule:
#     - cron: "0 20 * * 0-6"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: RUN
        run: |-
          docker rm -f essme
          docker rmi essme:0.0.1-SNAPSHOT
          ./mvnw spring-boot:build-image
          docker run -d -p 8005:8005 --net=host --name=essme essme:0.0.1-SNAPSHOT
          
